id: IAA6FFD9A
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T21:03:21.350641'
last_modified: '2022-06-18T21:03:21.350653'
parser: null
source_metadata:
  title: Hagiography of Chos rje chos Grags dpal bzang (1352–1434)
  author: snyoms las pa kun dga/
  description: 'Digital version 1.0 {Wylie}; WYLIE COPY of master xml (completed:
    2019-12-21); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Google Docs, OCR-processed (Tesseract)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:blo gsal don grub/ (ld)
  - Revisions/Corrections:blo gsal don grub/
  text_witnesses: https://sakyaresearch.org/sources/2388
  bases:
    7dc7:
      title: Hagiography of Chos rje chos Grags dpal bzang (1352–1434)
      order: 1
      base_file: 7dc7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
